project:
  type: website

website:
  title: "ISSS608-VAA"

  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
          - text: "Hands-on Exercise 1"
            href: Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.qmd
          - text: "Hands-on Exercise 2"
            href: Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02.qmd
          - text: "Hands-on Exercise 3 Part A"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03A.qmd
          - text: "Hands-on Exercise 3 Part B"
            href: Hands-on_Ex/Hands-on_Ex03/Hands-on_Ex03B.qmd
          - text: "Hands-on Exercise 4: Visualising Distribution"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex041.qmd
          - text: "Hands-on Exercise 4: Visual Statistical Analysis"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex042.qmd
          - text: "Hands-on Exercise 4: Visualising Uncertainty"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex043.qmd
          - text: "Hands-on Exercise 4: Building Funnel Plot with R"
            href: Hands-on_Ex/Hands-on_Ex04/Hands-on_Ex044.qmd
    right:
      - text: "Home"
        href: index.qmd
      - text: "About"
        href: about.qmd

format:
  html:
    theme: cosmo
    toc: true

editor: visual

